name: Android Build

on:
  push:
    branches:
      - master
      - master_dev

jobs:
  build:
     runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
      - uses: actions/checkout@v3
      with:
        distribution: 'temurin'
        java-version: '1_8'
        cache: 'gradle'

      - name: Build Project
        run: ./gradlew assembleDebug --stacktrace